### PR TITLE
HOTFIX ==K simplifier

### LINKED ISSUE #401: Booster appears to simplify non-`#Bottom` state to `#Bottom`
As per the bug reports attached, the simplification request `003_request.json` results in `#Bottom` when simplified by the booster, and not in `#Bottom` when simplified by the Haskell backend.

The pretty-print of the request is as follows:

```
petarmax@PetarMax kontrol-cse % pyk rpc-print out/kompiled report/rpc_CSE-LEMMAS-SPEC.cse-01-spec-g-succ-cc-eq/003_request.json 
JSON RPC request
id: 3
Method: simplify
State:
<generatedTop>
  <foundry>
    <kevm>
      <k>
        .K
      </k>
      <exit-code>
        EXITCODE_CELL:Int
      </exit-code>
      <mode>
        MODE_CELL:Mode
      </mode>
      <schedule>
        SCHEDULE:Schedule
      </schedule>
      <ethereum>
        <evm>
          <output>
            ?OUTPUT:Bytes
          </output>
          <statusCode>
            ?FINAL_STATUS:StatusCode
          </statusCode>
          <callStack>
            CALLSTACK_CELL:List
          </callStack>
          <interimStates>
            INTERIMSTATES_CELL:List
          </interimStates>
          <touchedAccounts>
            TOUCHED_ACCOUNTS:Set |Set SetItem ( ACCT_TO:Int )
          </touchedAccounts>
          <callState>
            <program>
              PROGRAM_CELL:Bytes
            </program>
            <jumpDests>
              JUMPDESTS_CELL:Set
            </jumpDests>
            <id>
              ACCT_TO:Int
            </id>
            <caller>
              CALLER_CELL:Account
            </caller>
            <callData>
              CALLDATA_CELL:Bytes
            </callData>
            <callValue>
              CALLVALUE_CELL:Int
            </callValue>
            <wordStack>
              ?OUTCOME:Int : WS:WordStack
            </wordStack>
            <localMem>
              LM:Bytes [ RETSTART:Int := #range ( ?OUTPUT:Bytes , 0 , minInt ( RETWIDTH:Int , lengthBytes ( ?OUTPUT:Bytes ) ) ) ]
            </localMem>
            <pc>
              PC_CELL:Int
            </pc>
            <gas>
              GAS_CELL:Gas
            </gas>
            <memoryUsed>
              MEMORYUSED_CELL:Int
            </memoryUsed>
            <callGas>
              CALLGAS_CELL:Gas
            </callGas>
            <static>
              false
            </static>
            <callDepth>
              CD:Int
            </callDepth>
          </callState>
          <substate>
            <selfDestruct>
              SELFDESTRUCT_CELL:Set
            </selfDestruct>
            <log>
              LOG_CELL:List
            </log>
            <refund>
              REFUND_CELL:Int
            </refund>
            <accessedAccounts>
              ACCESSED_ACCOUNTS:Set |Set SetItem ( ACCT_TO:Int )
            </accessedAccounts>
            <accessedStorage>
              ACCT_TO:Int |-> ACCT_TO_ACCESSED_STORAGE:Set |Set SetItem ( 0 ) SetItem ( 1 ) ACCESSEDSTORAGE_CELL_81a57323:Map
            </accessedStorage>
          </substate>
          <gasPrice>
            GASPRICE_CELL:Int
          </gasPrice>
          <origin>
            ORIGIN_CELL:Account
          </origin>
          <blockhashes>
            BLOCKHASHES_CELL:List
          </blockhashes>
          <block>
            <previousHash>
              PREVIOUSHASH_CELL:Int
            </previousHash>
            <ommersHash>
              OMMERSHASH_CELL:Int
            </ommersHash>
            <coinbase>
              COINBASE_CELL:Int
            </coinbase>
            <stateRoot>
              STATEROOT_CELL:Int
            </stateRoot>
            <transactionsRoot>
              TRANSACTIONSROOT_CELL:Int
            </transactionsRoot>
            <receiptsRoot>
              RECEIPTSROOT_CELL:Int
            </receiptsRoot>
            <logsBloom>
              LOGSBLOOM_CELL:Bytes
            </logsBloom>
            <difficulty>
              DIFFICULTY_CELL:Int
            </difficulty>
            <number>
              NUMBER_CELL:Int
            </number>
            <gasLimit>
              GASLIMIT_CELL:Int
            </gasLimit>
            <gasUsed>
              GASUSED_CELL:Gas
            </gasUsed>
            <timestamp>
              TIMESTAMP_CELL:Int
            </timestamp>
            <extraData>
              EXTRADATA_CELL:Bytes
            </extraData>
            <mixHash>
              MIXHASH_CELL:Int
            </mixHash>
            <blockNonce>
              BLOCKNONCE_CELL:Int
            </blockNonce>
            <baseFee>
              BASEFEE_CELL:Int
            </baseFee>
            <withdrawalsRoot>
              WITHDRAWALSROOT_CELL:Int
            </withdrawalsRoot>
            <ommerBlockHeaders>
              OMMERBLOCKHEADERS_CELL:JSON
            </ommerBlockHeaders>
          </block>
        </evm>
        <network>
          <chainID>
            CHAINID_CELL:Int
          </chainID>
          <accounts>
            <account>
              <acctID>
                ACCT_TO:Int
              </acctID>
              <balance>
                ACCT_TO_BAL:Int
              </balance>
              <code>
                ACCT_TO_CODE:Bytes
              </code>
              <storage>
                0 |-> ACCT_TO_SS_0:Int +Int 1 1 |-> ACCT_TO_SS_1:Int +Int 1 STORAGE_CELL_660440d3:Map
              </storage>
              <origStorage>
                ORIGSTORAGE_CELL:Map
              </origStorage>
              <nonce>
                ACCT_TO_NONCE:Int
              </nonce>
            </account> ACCOUNTS_CELL_347ae03a:AccountCellMap
          </accounts>
          <txOrder>
            TXORDER_CELL:List
          </txOrder>
          <txPending>
            TXPENDING_CELL:List
          </txPending>
          <messages>
            MESSAGES_CELL:MessageCellMap
          </messages>
        </network>
      </ethereum>
    </kevm>
    <cheatcodes>
      <prank>
        <prevCaller>
          PREVCALLER_CELL:Account
        </prevCaller>
        <prevOrigin>
          PREVORIGIN_CELL:Account
        </prevOrigin>
        <newCaller>
          NEWCALLER_CELL:Account
        </newCaller>
        <newOrigin>
          NEWORIGIN_CELL:Account
        </newOrigin>
        <active>
          ACTIVE_CELL:Bool
        </active>
        <depth>
          DEPTH_CELL:Int
        </depth>
        <singleCall>
          SINGLECALL_CELL:Bool
        </singleCall>
      </prank>
      <expectedRevert>
        <isRevertExpected>
          false
        </isRevertExpected>
        <expectedReason>
          EXPECTEDREASON_CELL:Bytes
        </expectedReason>
        <expectedDepth>
          EXPECTEDDEPTH_CELL:Int
        </expectedDepth>
      </expectedRevert>
      <expectedOpcode>
        <isOpcodeExpected>
          false
        </isOpcodeExpected>
        <expectedAddress>
          EXPECTEDADDRESS_CELL:Account
        </expectedAddress>
        <expectedValue>
          EXPECTEDVALUE_CELL:Int
        </expectedValue>
        <expectedData>
          EXPECTEDDATA_CELL:Bytes
        </expectedData>
        <opcodeType>
          OPCODETYPE_CELL:OpcodeType
        </opcodeType>
      </expectedOpcode>
      <expectEmit>
        <recordEvent>
          RECORDEVENT_CELL:Bool
        </recordEvent>
        <isEventExpected>
          ISEVENTEXPECTED_CELL:Bool
        </isEventExpected>
        <checkedTopics>
          CHECKEDTOPICS_CELL:List
        </checkedTopics>
        <checkedData>
          CHECKEDDATA_CELL:Bool
        </checkedData>
        <expectedEventAddress>
          EXPECTEDEVENTADDRESS_CELL:Account
        </expectedEventAddress>
      </expectEmit>
      <whitelist>
        <isCallWhitelistActive>
          false
        </isCallWhitelistActive>
        <isStorageWhitelistActive>
          false
        </isStorageWhitelistActive>
        <addressSet>
          ADDRESSSET_CELL:Set
        </addressSet>
        <storageSlotSet>
          STORAGESLOTSET_CELL:Set
        </storageSlotSet>
      </whitelist>
    </cheatcodes>
    <noGas>
      true
    </noGas>
  </foundry>
  <generatedCounter>
    GENERATEDCOUNTER_CELL_6b29af59:Int
  </generatedCounter>
</generatedTop>
#And { true #Equals 0 <=Int X:Int }
#And { true #Equals CD:Int <Int 1023 }
#And { true #Equals 0 <=Int VALUE:Int }
#And { true #Equals VALUE:Int ==Int 0 }
#And { true #Equals 0 <=Int ACCT_TO:Int }
#And { true #Equals 0 <=Int ARGSTART:Int }
#And { true #Equals 0 <=Int RETSTART:Int }
#And { true #Equals ?OUTCOME:Int ==Int 1 }
#And { true #Equals ARGWIDTH:Int ==Int 36 }
#And { true #Equals RETWIDTH:Int ==Int 32 }
#And { true #Equals 0 <=Int ACCT_TO_BAL:Int }
#And { true #Equals 0 <=Int ACCT_TO_SS_0:Int }
#And { true #Equals 0 <=Int ACCT_TO_SS_1:Int }
#And { true #Equals 0 <=Int ACCT_TO_NONCE:Int }
#And { true #Equals VALUE:Int <=Int ACCT_TO_BAL:Int }
#And { true #Equals ACCT_TO_NONCE:Int <Int maxUInt64 }
#And { true #Equals ACCT_TO:Int <Int pow160 }
#And { true #Equals ACCT_TO:Int =/=Int 645326474426547203313410069153905908525362434349 }
#And { true #Equals X:Int <Int pow256 }
#And { true #Equals VALUE:Int <Int pow256 }
#And { true #Equals ARGSTART:Int <Int pow256 }
#And { true #Equals RETSTART:Int <Int pow256 }
#And { true #Equals Ghasshift << SCHEDULE:Schedule >> }
#And { true #Equals ACCT_TO_BAL:Int <Int pow256 }
#And { true #Equals Ghasrevert << SCHEDULE:Schedule >> }
#And { true #Equals ACCT_TO_SS_0:Int <Int pow256 }
#And { true #Equals ACCT_TO_SS_1:Int <Int pow256 }
#And { true #Equals Ghasaccesslist << SCHEDULE:Schedule >> }
#And { true #Equals Ghasreturndata << SCHEDULE:Schedule >> }
#And { true #Equals ?FINAL_STATUS:StatusCode ==K EVMC_SUCCESS }
#And { true #Equals #sizeWordStack ( WS:WordStack ) <=Int 1023 }
#And { true #Equals notBool #isPrecompiledAccount ( ACCT_TO:Int , SCHEDULE:Schedule ) }
#And { true #Equals ACCT_TO_SS_0:Int +Int 1 <Int pow256 }
#And { true #Equals ACCT_TO_SS_1:Int +Int 1 <Int pow256 }
#And { true #Equals #range ( LM:Bytes , ARGSTART:Int , 4 ) ==K b"\xe4 &J" }
#And { true #Equals X:Int ==Int #asWord ( #range ( LM:Bytes , ARGSTART:Int +Int 4 , 32 ) ) }
#And { true #Equals X:Int +Int maxUInt160 &Int X:Int +Int 1 <Int pow256 }
#And { true #Equals ?OUTPUT:Bytes ==K #buf ( 32 , X:Int +Int maxUInt160 &Int X:Int +Int 1 ) }
#And { true #Equals ACCT_TO_CODE:Bytes ==K b"`\x80`@R4\x80\x15a\x00\x10W`\x00\x80\xfd[P`\x046\x10a\x00LW`\x005`\xe0\x1c\x80c\t\xb1[J\x14a\x00QW\x80c1\xc1b\x9f\x14a\x00vW\x80c]t-8\x14a\x00\x7fW\x80c\xe4 &J\x14a\x00\x88W[`\x00\x80\xfd[a\x00da\x00_6`\x04a\x01zV[a\x00\x9bV[`@Q\x90\x81R` \x01`@Q\x80\x91\x03\x90\xf3[a\x00d`\x00T\x81V[a\x00d`\x01T\x81V[a\x00da\x00\x966`\x04a\x01\xcdV[a\x00\xe6V[`\x00\x80T\x81\x80a\x00\xaa\x83a\x01\xfcV[\x91\x90PUP\x81a\x00\xbbW`\x00a\x00\xbeV[`\x01[`\xff\x16a\x00\xd4`\x01`\x01`\xa0\x1b\x03\x85\x16\x86a\x02\x15V[a\x00\xde\x91\x90a\x02\x15V[\x94\x93PPPPV[`\x01\x80T`\x00\x91\x82a\x00\xf7\x83a\x01\xfcV[\x90\x91UPP`@Qc\x04\xd8\xad\xa5`\xe1\x1b\x81R`\x04\x81\x01\x83\x90R`\x01`\x01`\xa0\x1b\x03\x83\x16`$\x82\x01R`\x01`D\x82\x01R0\x90c\t\xb1[J\x90`d\x01` `@Q\x80\x83\x03\x81`\x00\x87Z\xf1\x15\x80\x15a\x01PW=`\x00\x80>=`\x00\xfd[PPPP`@Q=`\x1f\x19`\x1f\x82\x01\x16\x82\x01\x80`@RP\x81\x01\x90a\x01t\x91\x90a\x02(V[\x92\x91PPV[`\x00\x80`\x00``\x84\x86\x03\x12\x15a\x01\x8fW`\x00\x80\xfd[\x835\x92P` \x84\x015`\x01`\x01`\xa0\x1b\x03\x81\x16\x81\x14a\x01\xadW`\x00\x80\xfd[\x91P`@\x84\x015\x80\x15\x15\x81\x14a\x01\xc2W`\x00\x80\xfd[\x80\x91PP\x92P\x92P\x92V[`\x00` \x82\x84\x03\x12\x15a\x01\xdfW`\x00\x80\xfd[P5\x91\x90PV[cNH{q`\xe0\x1b`\x00R`\x11`\x04R`$`\x00\xfd[`\x00`\x01\x82\x01a\x02\x0eWa\x02\x0ea\x01\xe6V[P`\x01\x01\x90V[\x80\x82\x01\x80\x82\x11\x15a\x01tWa\x01ta\x01\xe6V[`\x00` \x82\x84\x03\x12\x15a\x02:W`\x00\x80\xfd[PQ\x91\x90PV\xfe\xa2dipfsX\"\x12 |c\xef\xc9\x83'\x13\xb4\xe8\xac\x8a\xf6\xc5.\xe1\xa2[\xa0\xde\xa4\x19\xcf\xbe\xb0\x97\xaf\x9fG!_\xc2!dsolcC\x00\x08\x11\x003" }
```

[report-hb.zip](https://github.com/runtimeverification/hs-backend-booster/files/13523293/report-hb.zip)
[report-booster.zip](https://github.com/runtimeverification/hs-backend-booster/files/13523294/report-booster.zip)

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
An embarrassing mistake...thankfully an easy fix!

Fixes #401

### CODE REVIEW

**Comment by ehildenb** [comment]
Let's add a test! Do we have tests of each case of the `==K` simplifier above? Let's add them now if not!

File: library/Booster/Pattern/ApplyEquations.hs [hunk 1]
```diff
@@ -745,8 +745,6 @@ simplifyConstraint' recurseIntoEvalBool = \case
         | isConstructorSymbol symbol = pure FalseBool
     evalEqualsK KSet{} (SymbolApplication symbol _ _)
         | isConstructorSymbol symbol = pure FalseBool
```
Comment (ehildenb) [inline library/Booster/Pattern/ApplyEquations.hs:747]: This seems like it's probably not true?

What about two terms like `KSet(1, 2)` (internalized set), and `SetItem(1) |Set SetItem(2) |Set SetItem(2)`? These should be considered equal.

File: library/Booster/Pattern/ApplyEquations.hs [hunk 2]
```diff
@@ -745,8 +745,6 @@ simplifyConstraint' recurseIntoEvalBool = \case
...
-    evalEqualsK _ (SymbolApplication symbol _ _)
-        | isConstructorSymbol symbol = pure FalseBool
     evalEqualsK (Injection s1L s2L l) (Injection s1R s2R r)
         | s1L == s1R && s2L == s2R = evalEqualsK l r
```
Comment (ehildenb) [inline library/Booster/Pattern/ApplyEquations.hs:749]: This seems too restrictive, but maybe that's OK because it just won't handle some cases?

What about `inj(A, B){inj(B, C){term}}` and `inj(A, C){term}`?

File: library/Booster/Pattern/ApplyEquations.hs (hunk 1 above)
Comment (PetarMax) [reply library/Booster/Pattern/ApplyEquations.hs:747]: I'm not familiar with the implementation - does `SymbolApplication` include things like `|Set`? In that case, could internalized maps and maps with map updates result in the same issue?

Comment (goodlyrottenapple) [reply library/Booster/Pattern/ApplyEquations.hs:747]: sets are internalised, so there should be no possibility of KSet and a SymbolApplication being the same

Comment (ehildenb) [reply library/Booster/Pattern/ApplyEquations.hs:747]: What about the above case though? Are symbols `_|Set_` internalized? It's a function, not a constructor. Do we have a test of this case?

Comment (goodlyrottenapple) [reply library/Booster/Pattern/ApplyEquations.hs:747]: This case only applies to symbol applications of constructors. That's what the guard `| isConstructorSymbol symbol` is for. Since `_|Set_` is a function symbol, this case does not apply.

**Review by geo2a — APPROVED** [review]
