### PR TITLE
271 recursive simplification of constraints during evaluation

### LINKED ISSUE #271: Investigate recursive constraint evaluation / possibly experiment with caching
Issues https://github.com/runtimeverification/hs-backend-booster/issues/255 and https://github.com/runtimeverification/hs-backend-booster/issues/243 are reopened because of reverting the recursive constraint evaluation.

The reason for the revert was a regression in test `ERC20Test.testAllowance` (see description in #265).

- [ ] Investigate what exactly the regression is (extended logging and analysis)
- [ ] Aim to undo the revert, applying fixes where necessary

### PR DESCRIPTION
**Pull request by jberthold**
* recursive simplification of side conditions in rewrite rules and equations
* restrict recursion depth to a small value (5, not 100)
* modified simplification integration tests, including a description.  
   - now executes with booster-dev only
  - added a test that would loop in kore-rpc-booster or kore-rpc-dev

Fixes #271

### CODE REVIEW

**Comment by jberthold** [comment]
KEVM timings vs latest master: a few improvements

| Test                              | 271-recursive-simplification-reprise time | master-a673bb5 time | (271-recursive-simplification-reprise/master-a673bb5) time 
|-----------------------------------|-------------------------------------------|---------------------|------------------------------------------------------------
| benchmarks/encode-keccak00-spec.k | 43.47                                     | 48.37               | 0.8986975397973951                                         
| benchmarks/bytes00-spec.k         | 67.29                                     | 71.64               | 0.9392797319933                                            
| erc20/ds/approve-success-spec.k   | 55.59                                     | 58.38               | 0.9522096608427544                                         
| erc20/hkg/approve-spec.k          | 46.46                                     | 48.13               | 0.9653023062538957                                         
| TOTAL                             | 212.81000000000003                        | 226.51999999999998  | 0.939475542998411

**Comment by geo2a** [comment]
Kontrol performance (5 workers): some improvements and some really weird looking regressions, perhaps due to noise? rerunning with 1 worker.
| Test                                                                   | 271-recursive-simplification-reprise time | master-a673bb5 time | (271-recursive-simplification-reprise/master-a673bb5) time
|------------------------------------------------------------------------|-------------------------------------------|---------------------|------------------------------------------------------------
| AssumeTest.test_multi_assume(address,address)                          | 143.23                                    | 197.72              | 0.7244082540967024
| StoreTest.testGasLoadWarmUp()                                          | 75.22                                     | 98.43               | 0.7641979071421314
| ExpectRevertTest.test_expectRevert_message()                           | 113.35                                    | 132.59              | 0.8548910174221283
| SymbolicStorageTest.testEmptyInitialStorage(uint256)                   | 50.98                                     | 59.19               | 0.8612941375232303
| SymbolicStorageTest.testFail_SymbolicStorage(uint256)                  | 141.08                                    | 161.01              | 0.8762188683932677
| AllowChangesTest.testFailAllowChangesToStorage()                       | 197.52                                    | 217.94              | 0.9063044874736167
| BytesTypeTest.test_bytes4(bytes4)                                      | 48.9                                      | 51.63               | 0.94712376525276
| ArithmeticTest.test_max1(uint256,uint256)                              | 103.38                                    | 107.1               | 0.965266106442577
| StoreTest.testStoreLoadNonExistent()                                   | 99.69                                     | 95.64               | 1.0423462986198244
| LabelTest.testLabel()                                                  | 37.89                                     | 36.04               | 1.0513318534961156
| AddrTest.test_builtInAddresses()                                       | 28.35                                     | 26.67               | 1.0629921259842519
| ExpectRevertTest.test_ExpectRevert_increasedDepth()                    | 204.28                                    | 188.54              | 1.0834836109048478
| BlockParamsTest.testWarp(uint256)                                      | 46.82                                     | 43.04               | 1.087825278810409
| BlockParamsTest.testChainId(uint256)                                   | 54.55                                     | 44.42               | 1.2280504277352542
| StoreTest.testGasStoreWarmUp()                                         | 98.69                                     | 73.2                | 1.3482240437158468
| ArithmeticTest.test_max2(uint256,uint256)                              | 89.86                                     | 65.96               | 1.3623408126137053
| src/tests/integration/test_foundry_prove.py::test_foundry_resume_proof | 117.51                                    | 86.13               | 1.3643329850226402
| AssumeTest.test_assume_false(uint256,uint256)                          | 111.81                                    | 80.91               | 1.381905821282907
| StoreTest.testLoadNonExistent()                                        | 66.73                                     | 46.22               | 1.443747295543055
| BlockParamsTest.testFee(uint256)                                       | 62.07                                     | 42.6                | 1.4570422535211267
| BlockParamsTest.testBlockNumber()                                      | 39.45                                     | 25.76               | 1.531444099378882
| BlockParamsTest.testCoinBase()                                         | 58.11                                     | 37.53               | 1.5483613109512389
| BlockParamsTest.testRoll(uint256)                                      | 64.72                                     | 40.51               | 1.5976302147617873
| BMCLoopsTest.test_countdown_concrete()                                 | 25.32                                     | 4.52                | 5.601769911504426
| TOTAL                                                                  | 2079.5099999999998                        | 1963.3000000000004  | 1.0591911577446134

File: library/Booster/Pattern/ApplyEquations.hs [hunk 1]
```diff
@@ -632,17 +693,29 @@ applyEquation term rule = fmap (either id Success) $ runExceptT $ do
...
         (Predicate -> ApplyEquationResult) ->
         Predicate ->
         ExceptT ApplyEquationResult (EquationT io) (Maybe Predicate)
-    checkConstraint whenBottom (Predicate p) =
-        lift (simplifyConstraint' False p) >>= \case
-            FalseBool -> throwE $ whenBottom $ coerce p
+    checkConstraint whenBottom (Predicate p) = do
+        logOther (LevelOther "Simplify") $
+            "Recursive simplification of predicate: " <> pack (renderDefault (pretty p))
+        let fallBackToP :: EquationFailure -> EquationT io Term
```
Comment (geo2a) [inline library/Booster/Pattern/ApplyEquations.hs:706]:
```suggestion
        let fallBackToUnsimplified :: EquationFailure -> EquationT io Term
```

(nit-pick) I think this would be a better name

File: library/Booster/Pattern/ApplyEquations.hs [hunk 2]
```diff
@@ -171,10 +203,20 @@ isSuccess _ = False
...
+    EquationState
+        { termStack = []
+        , recursionStack = []
+        , changed = False
+        , predicates = mempty
+        , trace = mempty
+        , cache
+        }
+
+eqState :: MonadLoggerIO io => StateT EquationState io a -> EquationT io a
```
Comment (geo2a) [inline library/Booster/Pattern/ApplyEquations.hs:215]: nice!

File: library/Booster/Pattern/ApplyEquations.hs [hunk 3]
```diff
@@ -632,17 +693,29 @@ applyEquation term rule = fmap (either id Success) $ runExceptT $ do
                     pure $ substituteInTerm subst rule.rhs
                 unclearConditions -> throwE $ IndeterminateCondition unclearConditions
   where
-    -- evaluate/simplify a predicate, cut the operation short when it
-    -- is Bottom.
+    -- Simplify given predicate in a nested EquationT execution.
+    -- Return Nothing immediately if it is Bottom, return (Just
```
Comment (geo2a) [inline library/Booster/Pattern/ApplyEquations.hs:697]: Something that crossed my mind while looking at this code: 

According to the comment, `checkConstraint` returns `Just Nothing` if a constraint is true. If we end up with `[Just Nothing]`, than that would cause us to throw `IndeterminateCondition [Just Nothing]` in `applyEquation`.

However, the comment seems to be wrong: we will not return `Nothing` on false, but rather throw an exception, while `Nothing` will be returned on true and correctly filtered out by `catMaybes`.

**Comment by ehildenb** [comment]
Do we have any examples where this allows execution to continue where it couldn't before? If we don't see significant performance improvements, then we should at least check that we are indeed falling back less. Can we post fallback statistics here?

**Comment by jberthold** [comment]
> Do we have any examples where this allows execution to continue where it couldn't before? If we don't see significant performance improvements, then we should at least check that we are indeed falling back less. Can we post fallback statistics here?

The code change enables jump condition simplifications when combined with the `evm-semantics` change to add `preserves-definedness` attributes to some key simplifications.
 
> The worry I have is that recursive constraint simplification has _always_ caused problems in the past and been tricky to implement, usually with creating potentially infinite looping code. Do we have any protections against infinite looping? Is the depth-limit of 5 mentioned above doing that? Is that user-configurable?

The limit of 5 is currently not configurable but we can add an option to adjust that limit. There is one test with two mutually-recursive simplifications, which indeed loops forever in the legacy backend but is caught by the new code.

File: library/Booster/Pattern/ApplyEquations.hs (hunk 3 above)
Comment (jberthold) [reply library/Booster/Pattern/ApplyEquations.hs:697]: Good catch! I think this comment was explaining what a prior version without `whenBottom` was doing, which had a nest of `MaybeT ... (Maybe Predicate)` and got changed meanwhile. I adjusted the description.

**Comment by geo2a** [comment]
Kontrol performance with 3 workers
| Test                                                                   | 271-recursive-simplification-reprise time | master-a673bb5 time | (271-recursive-simplification-reprise/master-a673bb5) time
|------------------------------------------------------------------------|-------------------------------------------|---------------------|------------------------------------------------------------
| Setup2Test.test_setup()                                                | 42.73                                     | 57.1                | 0.7483362521891418
| BytesTypeTest.test_bytes4(bytes4)                                      | 29.17                                     | 33.64               | 0.8671224732461356
| AllowChangesTest.testFailAllowChangesToStorage()                       | 183.9                                     | 196.82              | 0.9343562646072554
| ArithmeticTest.test_max1(uint256,uint256)                              | 96.85                                     | 93.47               | 1.0361613351877608
| BMCLoopsTest.test_countdown_concrete()                                 | 25.04                                     | 24.04               | 1.0415973377703827
| AccountParamsTest.test_Nonce_NonExistentAddress()                      | 63.54                                     | 60.89               | 1.0435211036294958
| BlockParamsTest.testWarp(uint256)                                      | 42.04                                     | 40.25               | 1.044472049689441
| AssumeTest.test_assume_staticCall(bool)                                | 54.68                                     | 52.09               | 1.0497216356306391
| Empty.sol                                                              | 68.16                                     | 64.72               | 1.0531520395550062
| MethodDisambiguateTest.test_method_call()                              | 26.11                                     | 23.95               | 1.090187891440501
| ArithmeticTest.test_max2(uint256,uint256)                              | 80.1                                      | 61.82               | 1.2956971853769006
| StoreTest.testGasLoadWarmUp()                                          | 92.41                                     | 71.05               | 1.3006333567909922
| src/tests/integration/test_foundry_prove.py::test_foundry_resume_proof | 111.21                                    | 80.36               | 1.3838974614235937
| AssumeTest.test_assume_false(uint256,uint256)                          | 105.81                                    | 75.11               | 1.4087338570097192
| AssumeTest.testFail_assume_true(uint256,uint256)                       | 99.32                                     | 68.66               | 1.4465482085639383
| TOTAL                                                                  | 1121.07                                   | 1003.97             | 1.1166369513033256

**Review by geo2a — APPROVED** [review]
